-- 연습문제

CREATE TABLE MAJOR(
		MAJOR_NO NUMBER PRIMARY KEY,
		MAJOR_NM VARCHAR2(100) NOT NULL
);

CREATE TABLE STUDENT(
		STUDENT_ID NUMBER PRIMARY KEY,
		STUDENT_NAME VARCHAR2(20) NOT NULL,
		GENDER VARCHAR(3) CHECK(GENDER IN('남','여')),
		BRITH DATE,
		MAJOR_NO NUMBER REFERENCES MAJOR(MAJOR_NO)
		
);

SELECT * FROM MAJOR;
SELECT * FROM STUDENT;


INSERT INTO MAJOR VALUES(1, '소프트웨어공학과');
INSERT INTO MAJOR VALUES(2, '컴퓨터공학과');
INSERT INTO MAJOR VALUES(3, '법학과');
INSERT INTO MAJOR VALUES(4, '전기전자과');
INSERT INTO MAJOR VALUES(5, '경제학과');

SELECT * FROM MAJOR;


INSERT INTO STUDENT VALUES(1, '가나다', '남', '1991-01-01', 5);
INSERT INTO STUDENT VALUES(2, '라마바', '여', '1992-02-02', 1);
INSERT INTO STUDENT VALUES(3, '사아자', '남', '1993-03-03', 4);
INSERT INTO STUDENT VALUES(4, '차카타', '여', '1994-04-04', 2);
INSERT INTO STUDENT VALUES(5, '파하', '남', '1995-05-05', 3);

SELECT * FROM STUDENT;


ALTER TABLE MAJOR RENAME COLUMN MAJOR_NM TO MAJOR_NAME;


SELECT * FROM MAJOR;









